{
    "openapi": "3.0.0",
    "info": {
        "title": "API BTM",
        "description": "API du site BTM",
        "contact": {
            "email": "contact@balancetonmatch.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "https://balancetonmatch.com/api",
            "description": "Demo API Server"
        }
    ],
    "paths": {
        "/clubs": {
            "get": {
                "tags": [
                    "clubs"
                ],
                "summary": "Find club by ID",
                "description": "Returns all clubs",
                "operationId": "getClubs",
                "security": [
                    {
                        "api_key": []
                    }
                ]
            },
            "put": {
                "tags": [
                    "clubs"
                ],
                "summary": "Update an existing club",
                "operationId": "updateClub",
                "security": [
                    {
                        "clubstore_auth": [
                            "write:clubs",
                            "read:clubs"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "clubs"
                ],
                "summary": "Add a new club to the store",
                "operationId": "addClub",
                "security": [
                    {
                        "clubstore_auth": [
                            "write:clubs",
                            "read:clubs"
                        ]
                    }
                ]
            }
        },
        "/clubs/{clubId}": {
            "get": {
                "tags": [
                    "clubs"
                ],
                "summary": "Find club by ID",
                "description": "Returns a single club",
                "operationId": "getClubById",
                "security": [
                    {
                        "api_key": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "clubs"
                ],
                "summary": "Updates a club in the store with form data",
                "operationId": "updateClubWithForm",
                "security": [
                    {
                        "clubstore_auth": [
                            "write:clubs",
                            "read:clubs"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "clubs"
                ],
                "summary": "Deletes a club",
                "operationId": "deleteClub",
                "security": [
                    {
                        "clubstore_auth": [
                            "write:clubs",
                            "read:clubs"
                        ]
                    }
                ]
            }
        },
        "/clubs/{clubId}/uploadImage": {
            "post": {
                "tags": [
                    "clubs"
                ],
                "summary": "uploads an image",
                "operationId": "uploadFile",
                "security": [
                    {
                        "clubstore_auth": [
                            "write:pets",
                            "read:pets"
                        ]
                    }
                ]
            }
        },
        "/comments": {
            "put": {
                "tags": [
                    "comment"
                ],
                "summary": "Update an existing comment",
                "operationId": "updateComment",
                "security": [
                    {
                        "commentstore_auth": [
                            "write:comments",
                            "read:comments"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "comment"
                ],
                "summary": "Add a new comment to the store",
                "operationId": "addComment",
                "security": [
                    {
                        "commentstore_auth": [
                            "write:comments",
                            "read:comments"
                        ]
                    }
                ]
            }
        },
        "/comments/{commentId}": {
            "get": {
                "tags": [
                    "comment"
                ],
                "summary": "Find comment by ID",
                "description": "Returns a single comment",
                "operationId": "getCommentById",
                "security": [
                    {
                        "api_key": []
                    }
                ]
            }
        },
        "/comment/{commentId}": {
            "post": {
                "tags": [
                    "comment"
                ],
                "summary": "Updates a comment in the store with form data",
                "operationId": "updateCommentWithForm",
                "security": [
                    {
                        "commentstore_auth": [
                            "write:comments",
                            "read:comments"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "comment"
                ],
                "summary": "Deletes a comment",
                "operationId": "deleteComment",
                "security": [
                    {
                        "commentstore_auth": [
                            "write:comments",
                            "read:comments"
                        ]
                    }
                ]
            }
        },
        "/comment/{commentId}/uploadImage": {
            "post": {
                "tags": [
                    "comment"
                ],
                "summary": "uploads an image",
                "operationId": "uploadFile",
                "security": [
                    {
                        "commentstore_auth": [
                            "write:pets",
                            "read:pets"
                        ]
                    }
                ]
            }
        },
        "/matchs": {
            "get": {
                "tags": [
                    "matchs"
                ],
                "summary": "Find match by ID",
                "description": "Returns all matchs",
                "operationId": "getMatchs",
                "security": [
                    {
                        "api_key": []
                    }
                ]
            },
            "put": {
                "tags": [
                    "matchs"
                ],
                "summary": "Update an existing match",
                "operationId": "updateMatch",
                "security": [
                    {
                        "matchstore_auth": [
                            "write:matchs",
                            "read:matchs"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "matchs"
                ],
                "summary": "Add a new match to the store",
                "operationId": "addMatch",
                "security": [
                    {
                        "matchstore_auth": [
                            "write:matchs",
                            "read:matchs"
                        ]
                    }
                ]
            }
        },
        "/matchs/{matchId}": {
            "get": {
                "tags": [
                    "matchs"
                ],
                "summary": "Find match by ID",
                "description": "Returns a single match",
                "operationId": "getMatchById",
                "security": [
                    {
                        "api_key": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "matchs"
                ],
                "summary": "Updates a match in the store with form data",
                "operationId": "updateMatchWithForm",
                "security": [
                    {
                        "matchstore_auth": [
                            "write:matchs",
                            "read:matchs"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "matchs"
                ],
                "summary": "Deletes a match",
                "operationId": "deleteMatch",
                "security": [
                    {
                        "matchstore_auth": [
                            "write:matchs",
                            "read:matchs"
                        ]
                    }
                ]
            }
        },
        "/matchs/{matchId}/uploadImage": {
            "post": {
                "tags": [
                    "matchs"
                ],
                "summary": "uploads an image",
                "operationId": "uploadFile",
                "security": [
                    {
                        "matchstore_auth": [
                            "write:pets",
                            "read:pets"
                        ]
                    }
                ]
            }
        },
        "/user": {
            "post": {
                "tags": [
                    "user"
                ],
                "summary": "Add a new user to the store",
                "operationId": "addUser",
                "security": [
                    {
                        "userstore_auth": [
                            "write:users",
                            "read:users"
                        ]
                    }
                ]
            }
        },
        "/users": {
            "put": {
                "tags": [
                    "user"
                ],
                "summary": "Update an existing user",
                "operationId": "updateUser",
                "security": [
                    {
                        "userstore_auth": [
                            "write:users",
                            "read:users"
                        ]
                    }
                ]
            }
        },
        "/user/findByStatus": {
            "get": {
                "tags": [
                    "user"
                ],
                "summary": "Finds Users by status",
                "description": "Multiple status values can be provided with comma separated string",
                "operationId": "findUsersByStatus",
                "deprecated": true,
                "security": [
                    {
                        "userstore_auth": [
                            "write:users",
                            "read:users"
                        ]
                    }
                ]
            }
        },
        "/user/findByTags": {
            "get": {
                "tags": [
                    "user"
                ],
                "summary": "Finds Users by tags",
                "description": "Muliple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.",
                "operationId": "findByTags",
                "security": [
                    {
                        "userstore_auth": [
                            "write:users",
                            "read:users"
                        ]
                    }
                ]
            }
        },
        "/users/{userId}": {
            "get": {
                "tags": [
                    "user"
                ],
                "summary": "Find user by ID",
                "description": "Returns a single user",
                "operationId": "getUserById",
                "security": [
                    {
                        "api_key": []
                    }
                ]
            }
        },
        "/user/{userId}": {
            "post": {
                "tags": [
                    "user"
                ],
                "summary": "Updates a user in the store with form data",
                "operationId": "updateUserWithForm",
                "security": [
                    {
                        "userstore_auth": [
                            "write:users",
                            "read:users"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "user"
                ],
                "summary": "Deletes a user",
                "operationId": "deleteUser",
                "security": [
                    {
                        "userstore_auth": [
                            "write:users",
                            "read:users"
                        ]
                    }
                ]
            }
        },
        "/user/{userId}/uploadImage": {
            "post": {
                "tags": [
                    "user"
                ],
                "summary": "uploads an image",
                "operationId": "uploadFile",
                "security": [
                    {
                        "userstore_auth": [
                            "write:pets",
                            "read:pets"
                        ]
                    }
                ]
            }
        }
    },
    "security": [
        []
    ]
}